### ISSUE TITLE
Command line in documentation can be simplified

### ISSUE THREAD

**Issue by egahlin** [marschall/jfr-jdbctemplate#1]
The documentation reads:

    -XX:+FlightRecorder
    -XX:StartFlightRecording=disk=true,dumponexit=true,filename=recording.jfr

In JDK 11, which is the first version that doesn't require -XX:+UnlockCommercialFeatures, it is sufficient with:

    -XX:StartFlightRecording:filename=recording.jfr

1) -XX:+FlightRecorder is only needed for releases prior to Oracle JDK 8u40.
2) In JDK 11, disk is true by default.
3) If a filename is specified, dumponexit is set to true implicitly. 
4) JDK 11 supports ":" as separator.

**Comment by marschall** [comment]
Wow, thanks a lot!
I only started this project two days ago. How did you find out about it?

**Comment by egahlin** [comment]
Google :)
